language: node_js
node_js:
- node
install:
- npm install gulp gulp-sass
- gem install sass
- gulp sass
script:
- echo "success"
deploy:
  provider: s3
  access_key_id: AKIAI5VBWMNY2MW3VG7Q
  secret_access_key:
    secure: yT2h9tnm6XoNBm+IcyTl1jlytd3jTHj74JfQjBVWoFmIKQ7nUH5Gc9naMm4TOTyfaDciQov0YUbVezouZYA4LeZ8Sj5327PXchTyFCJZBCqgAoaZyph5Kgn7FGIWqkvurWAero+4JkTfsEtK11VQbNZbU+G6P7bsJqfIDc/IiossCjm0Yog/Z4fXSFwgFJ6nf+3gNV2UxT9IoyygpPDU1pMxoqAzI/IC3rN+cEBOsQe/+MGgMzzq4Jbmmk/ktKwne/HBrGMQHyqmL2YZe9kyT1lHcn2IIQJRhbsJ9QeI+tYwy6B0t5Ky+ihQEwBmuWmFneGcyvrDkOlOtAKItUg2RbI5ipQshiOfMFjRZfF7r62Xz0TLtvGj2gmCe8Z9ntktwwCD/TMj+QAY6MfjadN1eHEuKaoPTQOTwg5Ue9tGOF8uVMF7Sm3Jscr3aaspybqHv7rAp75+1MK/dqeu1Z5vNBRVNBfpLrE2BRvERKj9023AKSRNUxj9yQKNBQ9SVyeKTQE8X3Qswg2Ewh6nS7NczEtZmV35/JyGDwcF/bSRLwzJjtI1sogwL5aoQqxYTRJ3IM2CWkg83FEe4Y0nHkdTnAGdbIFD4+03hUi+8Fwet0siR0D01jZBKtI1rJYqIbG3xw4sd9yLERDU/wqadF+SFYqce0C86t85FUqtVRJYXmo=
  bucket: sroubconsulting.com
  local_dir: src
  skip_cleanup: true
  region: us-east-2
  on:
    repo: ktadaline/Business-Website
    branch: Sroub-Consulting-Group
