language: node_js
node_js:
- node
install:
- npm install gulp gulp-sass
- gem install sass
- gulp sass
script:
- echo "success"
deploy:
  provider: s3
  access_key_id: AKIAI6YU34S6VAF4K2TA
  secret_access_key:
    secure: yzdkgxfoGoCn3igax7b302IGFBhvDTU8Ruk/uTqGALB1rhSiyCN/W3+JXpssj5biZVu6lgIGg77mMx0PeivF2WBtKkq2U9tLJjpm/J7NzN+QvkgFCAv109UTkVklcTycoB1a/ioqLXV2o0EsQIf1aakxBMKBCh3CWQ7ljvqrQSKep4sXk3u42VbJRuEsLWOAzEPa01XETbIJCMiyMsWZPeZ3NBMyFzpozybzPEd/2NRKPAIv7Ovc/Ryn1uPSlqfqd2DYC2U4KTueSipX/PaSlYSWhW9TKMfdJZxgUs7JAqzpKZy3xOVHbDYW5V39PaoFL079K7WHsVO7hZEVI092O+yPUTnCHIW6Qhv/twMGTwvgbg8XH3W6KvatHAWrK5332GcZWPf0mpILqYlEnoJ1lKovq9YA38AItE9ZNp1FLD2aY/g1eKNbP1MsRCLQOKJKL4L8T4arFRPZXN+ROSQuLdbXKBpI/Lz9xztowpaNoImqE5tJfrJcQotribV5mLND0dtWFjP/+H/LVUXWfSnLz1Ap6g05lRwgHKsQun4oZva83uU5J81MNuy7YVo3Nd2wMTWxy/9b0NTVFlKupyDSLlYhF3RI5KhRQtWpCpgfCiC3cghutcfp7H2DCHAMGSttNDY3WUzuIIXvfPGPRdlz4CWtbkwXaMvU3t86i4/CmJQ=
  bucket: sroubconsulting.com
  local-dir: src
  acl: public_read
  on:
    repo: ktadaline/Business-Website
    branch: Sroub-Consulting-Group
